---
# tasks file for zabbix_monitoring

- name: Установить python3-pip + обновить кэш
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Удалить несовместимые пакеты
  ansible.builtin.pip:
    name:
      - zabbix-api
      - zabbix-api-pyzbx
      - pyzabbix
      - py-zabbix
    state: absent

- name: Установить zabbix-api через pip
  ansible.builtin.pip:
    name: zabbix-api==0.5.4
    executable: pip3

- name: Получить Zabbix API auth token
  ansible.builtin.uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "Admin"
        password: "{{ zabbix_server_api_admin_password }}"
      id: 10
    status_code: 200
    timeout: 10
  register: zbx_auth
  no_log: true

- set_fact:
    zbx_token: "{{ zbx_auth.json.result }}"
  when: zbx_auth.json.result | length > 0

- name: Получить ID интерфейса Zabbix сервера
  ansible.builtin.uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zbx_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "hostinterface.get"
      params:
        filter:
          host: "Zabbix server"
      id: 20
    status_code: 200
    timeout: 20
  register: interface_info
  when: zbx_token is defined

- set_fact:
    zbx_agent_interface_id: "{{ interface_info.json.result[0].interfaceid }}"
  when: interface_info.json.result | length > 0

- name: Обновить имя zabbix-агента
  ansible.builtin.uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zbx_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "hostinterface.update"
      params:
        interfaceid: "{{ zbx_agent_interface_id }}"
        dns: "zabbix-agent"
        useip: 0
        port: "10050"
      id: 30
    status_code: 200
    timeout: 30
  when: zbx_token is defined
    and zbx_agent_interface_id is defined
  register: api_result
  changed_when: api_result.json.result is defined

- name: Вывести ответ API
  debug:
    var: api_result.json.result
  when: api_result.json.result is defined

- name: Выход из Zabbix API
  ansible.builtin.uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Authorization: "Bearer {{ zbx_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.logout"
      params: []
      id: 40
    status_code: 200
    timeout: 5
  when: zbx_token is defined
