---
# tasks file for zabbix_monitoring

- name: Ensure pip is installed (если pip3 нет в системе)
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Install zabbix-api via pip
  ansible.builtin.pip:
    name: zabbix-api
    executable: pip3

- name: Create a template for HTTP monitoring
  community.zabbix.zabbix_template:
    server_url: "http://{{ zabbix_server_ip }}/api_jsonrpc.php"
    login_user: Admin
    login_password: "{{ zabbix_server_api_admin_password }}"
    template_name: "MediaWiki Template HTTP Service Monitoring"
    template_groups:
      - "Templates"
    state: present
