---
# tasks file for zabbix_monitoring

- name: Установить python3-pip + обновить кэш
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Удалить несовместимые пакеты
  ansible.builtin.pip:
    name:
      - zabbix-api
      - zabbix-api-pyzbx
      - pyzabbix
      - py-zabbix
    state: absent

- name: Установить zabbix-api через pip
  ansible.builtin.pip:
    name: zabbix-api==0.5.4
    executable: pip3

- name: Получить Zabbix API auth token
  ansible.builtin.uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "Admin"
        password: "{{ zabbix_server_api_admin_password }}"
      id: 1
    status_code: 200
    timeout: 10
  register: zabbix_auth
  no_log: true

- name: Вывести zabbix_auth
  debug:
    var: zabbix_auth
  when: zabbix_auth is defined

# - name: Обновить имя zabbix-агента
#   ansible.builtin.uri:
#     url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
#     method: POST
#     headers:
#       Content-Type: "application/json-rpc"
#       Authorization: "Bearer {{ zabbix_auth.json.result }}"
#     body:
#       jsonrpc: "2.0"
#       method: "hostinterface.update"
#       params:
#         filter: {"host": "Zabbix server"}
#         interfaces: [{
#           "type": 1,
#           "main": 1,
#           "useip": 0,
#           "dns": "zabbix-agent",
#           "port": "10050"
#         }]
#       id: 2
#     status_code: 200
#     timeout: 30
#   register: api_result
#   changed_when: api_result.json.result is defined
#   when: zabbix_auth.json.result is defined

# - name: Вывести результат API запроса
#   debug:
#     var: api_result.json
#   when: api_result is defined

- name: Выход из Zabbix API
  ansible.builtin.uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zabbix_auth.json.result }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.logout"
      params: []
      id: 3
    status_code: 200
    timeout: 5
  register: api_logout_result
  when: zabbix_auth.json.result is defined

- name: Вывести api_logout_result
  debug:
    var: api_logout_result
  when: api_logout_result is defined
