---
# tasks file for pg_mediawiki

- name: Создание пользователя wikiuser
  postgresql_user:
    name: wikiuser
    password: "wikiuser"
    state: present
    role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE"

- name: Создание базы данных my_wiki
  postgresql_db:
    name: my_wiki
    owner: wikiuser
    state: present
