---
# tasks file for pg_mediawiki

- name: Установка psycopg2 (требуется для модулей PostgreSQL)
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
  become: true

- name: Создание пользователя wikiuser
  become: true
  become_user: postgres
  postgresql_user:
    name: wikiuser
    password: "{{ postgres_wikiuser_password }}"
    state: present
    role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE"
  become: true

- name: Создание базы данных my_wiki
  become: true
  become_user: postgres
  postgresql_db:
    name: my_wiki
    owner: wikiuser
    state: present
