---
# tasks file for php_install

- name: Остановить Nginx
  ansible.builtin.service:
    name: nginx
    state: stopped

- name: Отключить автозапуск Nginx
  ansible.builtin.service:
    name: nginx
    enabled: false

- name: Установить пакеты PHP
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ php_packages_to_install }}"
