---
# tasks file for mediawiki_install

- name: Скачать архив MediaWiki
  ansible.builtin.get_url:
    url: https://releases.wikimedia.org/mediawiki/1.42/mediawiki-1.42.1.tar.gz
    dest: /tmp/mediawiki-1.42.1.tar.gz
    mode: '0644'

- name: Проверить наличие каталога /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Распаковать MediaWiki в /var/www/html
  ansible.builtin.unarchive:
    src: /tmp/mediawiki-1.42.1.tar.gz
    dest: /var/www/html/
    remote_src: true
    extra_opts:
     - --strip-components=1

- name: Установить владельца /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: true

- name: Установить права /var/www/html
  ansible.builtin.file:
    path: /var/www/html
    mode: "u=rwX,go=rX"
    recurse: true

- name: Удалить index.html index.nginx-debian.html
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/www/html/index.html
    - /var/www/html/index.nginx-debian.html
  become: true



- name: Установить владельца LocalSettings.php
  ansible.builtin.file:
    path: /var/www/html/LocalSettings.php
    owner: www-data
    group: www-data

- name: Установить права LocalSettings.php
  ansible.builtin.file:
    path: /var/www/html/LocalSettings.php
    mode: '600'
