---
# tasks file for mediawiki_settings

# - name: Удалить конфиг MediaWiki
#   ansible.builtin.file:
#     path: /var/www/html/LocalSettings.php
#     state: absent
#   become: true

- name: Запустить install.php для настройки MediaWiki
  ansible.builtin.command: |
    php /var/www/html/maintenance/install.php \
      --confpath=/var/www/html \
      --dbname="my_wiki" \
      --dbuser="wikiuser" \
      --dbpass="{{ postgres_wikiuser_password }}" \
      --dbserver="{{ hostvars['vm2']['ansible_host'] }}" \
      --dbtype=postgres \
      --lang=ru \
      --pass="{{ mediawiki_admin_password }}" \
      --scriptpath="" \
      --server="http://{{ hostvars[inventory_hostname]['ansible_host'] }}" \
      "s20691161wiki" \
      "admin"
  become: true
  become_user: www-data
  args:
    creates: /var/www/html/LocalSettings.php  # Не запускать, если файл уже есть
  no_log: true  # Скрывает пароли в логах
  when: inventory_hostname == 'vm2'

- name: Создать временную директорию на control node
  ansible.builtin.file:
    path: /tmp/ansible_mediawiki_transfer
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true

- name: Скачать LocalSettings.php с vm2
  ansible.builtin.fetch:
    src: /var/www/html/LocalSettings.php
    dest: /tmp/ansible_mediawiki_transfer/LocalSettings.tmp
    flat: yes
  delegate_to: vm2
  run_once: true
  when: inventory_hostname == 'vm3'

- name: Загрузить конфиг на vm3
  ansible.builtin.copy:
    src: /tmp/ansible_mediawiki_transfer/LocalSettings.tmp
    dest: /var/www/html/LocalSettings.php
    remote_src: no  # Важно! Файл берется с control node
    owner: www-data
    group: www-data
    mode: '0600'
  when: inventory_hostname == 'vm3'

- name: Очистить временные файлы
  ansible.builtin.file:
    path: /tmp/ansible_mediawiki_transfer
    state: absent
  delegate_to: localhost
  run_once: true

- name: Заменить веб-сервер конфига vm3
  ansible.builtin.replace:
    path: /var/www/html/LocalSettings.php
    regexp: "(\\$wgServer\\s*=\\s*[\"']).*?([\"'])"
    replace: "\\1http://{{ hostvars[inventory_hostname]['ansible_host'] }}\\2"
  when: inventory_hostname == 'vm3'

- name: Установить права конфига MediaWiki
  ansible.builtin.file:
    path: /var/www/html/LocalSettings.php
    owner: www-data
    group: www-data
    mode: '600'
