---
# tasks file for mediawiki_s3_install

- name: Установить s3fs
  ansible.builtin.apt:
    name: s3fs
    state: present

- name: Создать credentials файл
  become_user: s20691161
  ansible.builtin.copy:
    dest: /home/s20691161/.passwd-s3fs
    content: "\
      {{ lookup('env', 'TF_VAR_yc_access_key_id') }}:\
      {{ lookup('env', 'TF_VAR_yc_secret_access_key') }}"
    mode: '0600'
  when: lookup('env', 'TF_VAR_yc_access_key_id') is defined
    and lookup('env', 'TF_VAR_yc_secret_access_key') is defined

- name: Создать точку монтирования
  ansible.builtin.file:
    path: /mnt/s3bucket
    state: directory
    mode: '0755'
    owner: s20691161
    group: s20691161

- name: Проверить, смонтирован ли уже бакет
  ansible.builtin.command: mountpoint -q /mnt/s3bucket
  ignore_errors: true
  register: mount_check
  changed_when: false

- name: Монтировать бакет
  become_user: s20691161
  ansible.builtin.command: >
    s3fs {{ wiki_s3_bucket }} /mnt/s3bucket
    -o url=https://storage.yandexcloud.net
    -o passwd_file=/home/s20691161/.passwd-s3fs
  when: mount_check.rc != 0
