---
# tasks file for mediawiki_s3_install

- name: Установить s3fs
  ansible.builtin.apt:
    name: s3fs
    state: present

- name: Создать credentials файл
  become_user: s20691161
  ansible.builtin.copy:
    dest: /home/s20691161/.passwd-s3fs
    content: "\
      {{ lookup('env', 'TF_VAR_yc_access_key_id') }}:\
      {{ lookup('env', 'TF_VAR_yc_secret_access_key') }}"
    mode: '0600'
  when: lookup('env', 'TF_VAR_yc_access_key_id') is defined
    and lookup('env', 'TF_VAR_yc_secret_access_key') is defined

- name: Проверить монтирование
  ansible.builtin.set_fact:
    is_mounted: >
      {{ ansible_mounts
      | selectattr('mount', 'equalto', '/mnt/s3bucket')
      | list
      | length > 0
      }}

- name: Отмонтировать бакет если смонтирован
  ansible.builtin.mount:
    path: /mnt/s3bucket
    state: unmounted
  when: is_mounted

- name: Создать точку монтирования
  ansible.builtin.file:
    path: /mnt/s3bucket
    state: directory
    owner: s20691161
    group: s20691161
    mode: '0755'

- name: Монтировать бакет
  become_user: s20691161
  ansible.builtin.mount:
    path: /mnt/s3bucket
    src: "{{ wiki_s3_bucket }}"
    fstype: fuse.s3fs
    opts: "url=https://storage.yandexcloud.net,passwd_file=/home/s20691161/.passwd-s3fs"
    state: mounted
