---
# tasks file for mediawiki_s3_install

- name: Установить s3fs
  ansible.builtin.apt:
    name: s3fs
    state: present

- name: Создать credentials файл
  become_user: s20691161
  ansible.builtin.copy:
    dest: /home/s20691161/.passwd-s3fs
    content: "\
      {{ lookup('env', 'TF_VAR_yc_access_key_id') }}:\
      {{ lookup('env', 'TF_VAR_yc_secret_access_key') }}"
    mode: '0600'
  when: lookup('env', 'TF_VAR_yc_access_key_id') is defined
    and lookup('env', 'TF_VAR_yc_secret_access_key') is defined

- name: Проверить монтирование через /proc/mounts
  ansible.builtin.shell: |
    if grep -q " /mnt/s3bucket " /proc/mounts; then
      echo "mounted"
    else
      echo "not mounted"
    fi
  register: mount_check
  changed_when: false
  ignore_errors: true

- name: Отмонтировать бакет если смонтирован
  ansible.builtin.command: umount /mnt/s3bucket
  when: "'mounted' in mount_check.stdout"

- name: Создать точку монтирования
  become_user: s20691161
  ansible.builtin.file:
    path: /mnt/s3bucket
    state: directory
    mode: '0755'

- name: Монтировать бакет
  become_user: s20691161
  ansible.builtin.command: >
    s3fs {{ wiki_s3_bucket }} /mnt/s3bucket
    -o url=https://storage.yandexcloud.net
    -o passwd_file=/home/s20691161/.passwd-s3fs
