---
# tasks file for mediawiki_s3_install

- name: Create credentials file from environment variables
  become_user: s20691161
  shell: |
    sudo apt-get install -y s3fs
    echo "{{ lookup('env', 'TF_VAR_yc_access_key_id') }}:{{ lookup('env', 'TF_VAR_yc_secret_access_key') }}" > /home/s20691161/.passwd-s3fs
    chmod 600 /home/s20691161/.passwd-s3fs
    sudo mkdir -p /mnt/s3bucket
    s3fs s3bucket-s20691161 /mnt/s3bucket \
      -o url=https://storage.yandexcloud.net \
      -o passwd_file=/home/s20691161/.passwd-s3fs
  args:
    executable: /bin/bash
  when: lookup('env', 'TF_VAR_yc_access_key_id') is defined and lookup('env', 'TF_VAR_yc_secret_access_key') is defined
