---
# tasks file for mediawiki_s3_install

- name: Install s3fs
  become: true
  apt:
    name: s3fs
    state: present

- name: Create credentials directory
  become_user: s20691161
  file:
    path: /home/s20691161/.s3fs
    state: directory
    mode: '0700'

- name: Create credentials file
  become_user: s20691161
  copy:
    dest: /home/s20691161/.passwd-s3fs
    content: "{{ lookup('env', 'TF_VAR_yc_access_key_id') }}:{{ lookup('env', 'TF_VAR_yc_secret_access_key') }}"
    mode: '0600'
  when: lookup('env', 'TF_VAR_yc_access_key_id') is defined and lookup('env', 'TF_VAR_yc_secret_access_key') is defined

- name: Create mount point
  become: true
  file:
    path: /mnt/s3bucket
    state: directory
    mode: '0777'  # Temporary wide permissions for testing

- name: Mount S3 bucket
  become: true
  command: >
    s3fs s3bucket-s20691161 /mnt/s3bucket
    -o url=https://storage.yandexcloud.net
    -o passwd_file=/home/s20691161/.passwd-s3fs
    -o allow_other
    -o umask=000
  when: lookup('env', 'TF_VAR_yc_access_key_id') is defined and lookup('env', 'TF_VAR_yc_secret_access_key') is defined
