---
# tasks file for zabbix_agent_install

- name: Установить zabbix-agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: Подменить zabbix_agentd.conf
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Перезапустить zabbix-agent и добавить в автозагрузку
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true

- name: Get Zabbix API auth token
  uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        user: "Admin"
        password: "{{ zabbix_server_api_admin_password }}"
      id: 1
    status_code: 200
    timeout: 5
  register: zabbix_auth
  #no_log: true

- name: Register host on Zabbix server
  uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "host.create"
      params:
        host: "{{ inventory_hostname }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
            port: "10050"
        groups:
          - groupid: "2"
      auth: "{{ zabbix_auth.json.result | default(omit) }}"
      id: 2
    status_code: 200
    timeout: 10
  register: host_registration
  when: zabbix_auth is succeeded and zabbix_auth.json.result is defined
