---
# tasks file for zabbix_agent_install

- name: Установить zabbix-agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: Подменить zabbix_agentd.conf
  ansible.builtin.template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: Перезапустить zabbix-agent и добавить в автозагрузку
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true

- name: Get Zabbix API auth token (Zabbix 7.2+)
  uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "Admin"  # Чувствительно к регистру!
        password: "{{ zabbix_server_api_admin_password }}"
      id: 1
    status_code: 200
    timeout: 10
  register: zabbix_auth
  no_log: true  # Скрывает пароль в логах
  ignore_errors: yes  # Продолжает выполнение при ошибке

- name: Debug - Show auth result (для диагностики)
  debug:
    var: zabbix_auth.json
  when: zabbix_auth.json is defined

- name: Register host on Zabbix server
  uri:
    url: "http://{{ zabbix_server_ip }}:8080/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "host.create"
      params:
        host: "{{ inventory_hostname }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_host }}"
            port: "10050"
        groups:
          - groupid: "2"  # Обычно "Linux servers"
      auth: "{{ zabbix_auth.json.result }}"
      id: 2
    status_code: 200
    timeout: 10
  when: zabbix_auth.json.result is defined
