---
# tasks file for pg_master_replica

- name: Мастер-сервер - Создать пользователя repuser
  become_user: postgres
  ansible.builtin.postgresql_user:
    name: repuser
    password: "{{ postgres_repuser_password }}"
    state: present
    role_attr_flags: "REPLICATION"
  when: inventory_hostname == wiki_db_master_vm

- name: Мастер-сервер - Настроить postgresql.conf для репликации
  ansible.builtin.replace:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?\\s*wal_level\\s*=\\s*\\S+"
    replace: 'wal_level = replica'
  when: inventory_hostname == wiki_db_master_vm
  notify: "restart postgresql"

- name: Мастер-сервер - Настроить pg_hba.conf для репликации
  ansible.builtin.blockinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    block: "\
      {% for host in groups['wiki_db'] %} \
      {% if host != wiki_db_master_vm %} \
      host    replication     repuser        \
      {{ hostvars[host]['ansible_host'] }}/32      \
      scram-sha-256 \
      {% endif %} \
      {% endfor %}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - REPLICATION"
    insertafter: EOF
  when: inventory_hostname == wiki_db_master_vm
  notify: "restart postgresql"

- name: Резервный сервер - Настроить postgresql.conf
  ansible.builtin.replace:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?\\s*hot_standby\\s*=\\s*\\S+"
    replace: 'hot_standby = on'
  when: inventory_hostname != wiki_db_master_vm
  notify: "restart postgresql"

- name: Резервный сервер - Остановить PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
  when: inventory_hostname != wiki_db_master_vm
  notify: "restart postgresql"

- name: Резервный сервер - Почистить каталог PostgreSQL
  ansible.builtin.file:
    path: /var/lib/postgresql/14/main/
    state: absent
  when: inventory_hostname != wiki_db_master_vm
  notify: "restart postgresql"

- name: Резервный сервер - Перенести данные мастера
  become_user: postgres
  ansible.builtin.command: "pg_basebackup \
    -h {{ wiki_db_master_ip }} \
    -D /var/lib/postgresql/14/main \
    -U repuser \
    -P \
    -v \
    -R"
  environment:
    PGPASSWORD: "{{ postgres_repuser_password }}"
  when: inventory_hostname != wiki_db_master_vm
  notify: "restart postgresql"
