---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа хостов
    nginx:  # Имя подгруппы хостов
      hosts:  # Узлы группы
        vm1:
          ansible_host: 89.169.179.72
        vm2:
          ansible_host: 89.169.183.226
        vm3:
          ansible_host: 89.169.177.209
        vm4:
          ansible_host: 89.169.179.1
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: s20691161  # имя пользователя
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # с другим пользователем после подключения
