---
linux:  # Группа хостов
  children:  # Обозначение, что будет подгруппа
    nginx:  # Имя подгруппы
      hosts:  # Узлы
        vm1:
          ansible_host: &vm1_ip 89.169.172.130
        vm2:
          ansible_host: &vm2_ip 89.169.179.103
        vm3:
          ansible_host: &vm3_ip 89.169.182.143
  vars:  # Переменные, доступные или используемые для всех подгрупп
    ansible_user: s20691161  # имя пользователя
    connection_protocol: ssh  # тип подключения
    ansible_become: true  # с другим пользователем после подключения

    wiki_proxy_vm: "vm1"
    wiki_proxy_ip: *vm1_ip

    wiki_pg_master_vm: "vm2"
    wiki_pg_master_ip: *vm2_ip
    wiki_pg_replica_vm: "vm3"
    wiki_pg_replica_ip: *vm3_ip

    zabbix_server_vm: "vm1"
    zabbix_server_ip: *vm1_ip
