---
- name: Изменение имени хоста и установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка nginx
  hosts: nginx  # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_install
  tags:
    - nginx_install

- name: Настройка проксирующего Nginx
  hosts: vm2  # Применяем только к vm2 (прокси-серверу)
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy
