---
- name: Изменение имени хоста и установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка nginx
  hosts: nginx  # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_install
  tags:
    - nginx_install
