---
- name: Изменение имени хоста и установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - default_packages

- name: Установка Nginx
  hosts: nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего Nginx
  hosts: vm1
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Update Upgrade
  hosts: vm2, vm3
  roles:
    - role: update_upgrade
  tags:
    - update_upgrade

- name: Установка PostgreSQL 14
  hosts: vm2, vm3
  roles:
    - role: pg_install
  tags:
    - pg_install

- name: Подготовка postgres MediaWiki
  hosts: vm2, vm3
  vars_files:
    - vars/vault/postgres_vault.yml
  roles:
    - role: pg_mediawiki
  tags:
    - pg_mediawiki

- name: Установка PHP
  hosts: vm2, vm3
  roles:
    - role: php_install
  tags:
    - php_install

- name: Установка MediaWiki
  hosts: vm2, vm3
  roles:
    - role: mediawiki_install
  tags:
    - mediawiki_install

- name: Первичная настройка MediaWiki
  hosts: vm2, vm3
  vars_files:
    - vars/vault/postgres_vault.yml
    - vars/vault/mediawiki_vault.yml
  roles:
    - role: mediawiki_settings
  tags:
    - mediawiki_settings

- name: Настройка postgres master-replica
  hosts: vm2, vm3
  vars_files:
    - vars/vault/postgres_vault.yml
  roles:
    - role: pg_master_replica
  tags:
    - pg_master_replica

- name: Установка Zabbix-сервера
  hosts: vm1
  roles:
    - role: zabbix_server
      vars:
        zabbix_server_database: mysql  # или postgresql
        zabbix_server_dbhost: "{{ hostvars['vm2']['ansible_host'] }}"
        zabbix_server_dbname: zabbix
        zabbix_server_dbuser: zabbix
        zabbix_server_dbpassword: "{{ zabbix_server_db_password }}"
        zabbix_server_install_frontend: true
        zabbix_server_web_server: nginx  # или apache
  tags:
    - zabbix_server_install
