---
- name: Изменение имени хоста и установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - default_packages

- name: Установка Nginx
  hosts: nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего Nginx
  hosts: vm1
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Update Upgrade
  hosts: vm2, vm3
  roles:
    - role: update_upgrade
  tags:
    - update_upgrade

- name: Установка PostgreSQL 14
  hosts: vm2, vm3
  roles:
    - role: pg_install
  tags:
    - pg_install

- name: Создание пользователя и базы данных MediaWiki
  hosts: vm2
  vars_files:
    - vars/vault/postgres_vault.yml
  roles:
    - role: pg_mediawiki
  tags:
    - pg_mediawiki

- name: Установка PHP
  hosts: vm2, vm3
  roles:
    - role: php_install
  tags:
    - php_install

- name: Установка MediaWiki
  hosts: vm2, vm3
  vars_files:
    - vars/vault/postgres_vault.yml
  roles:
    - role: mediawiki_install
  tags:
    - mediawiki_install
