---
- name: Установка имени хоста и стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - default_packages

- name: Установка Nginx и подмена главной веб-страницы
  hosts: nginx
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

- name: Настройка проксирующего Nginx
  hosts: wiki_proxy
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Обновление системы
  hosts: wiki_media
  roles:
    - role: update_upgrade
  tags:
    - update_upgrade

- name: Установка PostgreSQL 14
  hosts: wiki_db
  roles:
    - role: pg_install
  tags:
    - pg_install

- name: Подготовка базы данных MediaWiki
  hosts: wiki_db
  vars_files:
    - vars/vault/postgres_vault.yml
  roles:
    - role: pg_mediawiki
  tags:
    - pg_mediawiki

- name: Установка PHP
  hosts: wiki_media
  roles:
    - role: php_install
  tags:
    - php_install

- name: Установка MediaWiki
  hosts: vm2, vm3
  roles:
    - role: mediawiki_install
  tags:
    - mediawiki_install

- name: Первичная настройка MediaWiki
  hosts: vm2, vm3
  vars_files:
    - vars/vault/postgres_vault.yml
    - vars/vault/mediawiki_vault.yml
  roles:
    - role: mediawiki_settings
  tags:
    - mediawiki_settings

- name: Настройка postgres master-replica
  hosts: vm2, vm3
  vars_files:
    - vars/vault/postgres_vault.yml
  roles:
    - role: pg_master_replica
  tags:
    - pg_master_replica

- name: Установка Zabbix-сервера
  hosts: vm1
  roles:
    - role: zabbix_server_install
  tags:
    - zabbix_server_install
